class AppRoutes {
  static const String SPLASH_SCREEN_ROUTE = 'SPLASH_SCREEN_ROUTE';
  static const String SELECT_USER_SCREEN_ROUTE = 'SELECT_USER_SCREEN_ROUTE';
  static const String HOME_SCREEN_ROUTE = 'HOME_SCREEN_ROUTE';
  static const String LOGIN_SCREEN_ROUTE = 'LOGIN_SCREEN_ROUTE';
  static const String REGISTER_SCREEN_ROUTE = 'REGISTER_SCREEN_ROUTE';
  static const String FORGET_PASSWORD_SCREEN_ROUTE = 'FORGET_PASSWORD_SCREEN_ROUTE';
  static const String SELECT_COUNTRY_SCREEN_ROUTE = 'SELECT_COUNTRY_SCREEN_ROUTE';

}