class AppRoutes {
  static const String SPLASH_SCREEN_ROUTE = 'SPLASH_SCREEN_ROUTE';
  static const String SELECT_USER_SCREEN_ROUTE = 'SELECT_USER_SCREEN_ROUTE';
  static const String HOME_SCREEN_ROUTE = 'HOME_SCREEN_ROUTE';
  static const String LOGIN_SCREEN_ROUTE = 'LOGIN_SCREEN_ROUTE';
  static const String REGISTER_SCREEN_ROUTE = 'REGISTER_SCREEN_ROUTE';
  static const String FORGET_PASSWORD_SCREEN_ROUTE = 'FORGET_PASSWORD_SCREEN_ROUTE';
  static const String SELECT_COUNTRY_SCREEN_ROUTE = 'SELECT_COUNTRY_SCREEN_ROUTE';
  static const String EDIT_WORKING_TIMES_SCREEN_ROUTE = 'EDIT_WORKING_TIMES_SCREEN_ROUTE';
  static const String ADD_VACATION_SCREEN_ROUTE = 'ADD_VACATION_SCREEN_ROUTE';
  static const String CHANGE_LANGUAGE_SCREEN_ROUTE = 'CHANGE_LANGUAGE_SCREEN_ROUTE';
  static const String ABOUT_US_SCREEN_ROUTE = 'ABOUT_US_SCREEN_ROUTE';
  static const String DOCTOR_APPOINTMENTS_SCREEN_ROUTE = 'DOCTOR_APPOINTMENTS_SCREEN_ROUTE';
  static const String DOCTOR_APPOINTMENT_TIMES_SCREEN_ROUTE = 'DOCTOR_APPOINTMENT_TIMES_SCREEN_ROUTE';
  static const String DOCTOR_APPOINTMENTS_HOURS_SCREEN_ROUTE = 'DOCTOR_APPOINTMENTS_HOURS_SCREEN_ROUTE';
  static const String DOCTOR_BOOKING_SCREEN_ROUTE = 'DOCTOR_BOOKING_SCREEN_ROUTE';




}